name: EscapeToEverywhere
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39559230604209006
title: Follow Us Around the World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#031112'
    - '#5480b1'
    - '#bcc6cf'
    - '#c5793d'
    - '#ac3d23'
  brandStrength: 0.625
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
